FROM python:3.10-slim
WORKDIR /app
# This line is critical! It copies app.py AND your new scripts.
COPY . /app
RUN pip install streamlit openai PyPDF2 google-cloud-monitoring google-cloud-storage requests
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
